# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 506)
        MainWindow.setWindowOpacity(0.8)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result = QtWidgets.QLabel(parent=self.centralwidget)
        self.result.setGeometry(QtCore.QRect(0, 0, 401, 58))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        self.result.setFont(font)
        self.result.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(114, 255, 246, 255));\n"
"color: rgb(255, 255, 255);")
        self.result.setObjectName("result")
        self.btnZero = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnZero.setGeometry(QtCore.QRect(0, 406, 150, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btnZero.setFont(font)
        self.btnZero.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btnZero.setObjectName("btnZero")
        self.btnEqual = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEqual.setGeometry(QtCore.QRect(150, 406, 150, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btnEqual.setFont(font)
        self.btnEqual.setStyleSheet("background-color: rgb(255, 85, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.btnEqual.setObjectName("btnEqual")
        self.btn2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(100, 307, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btn2.setObjectName("btn2")
        self.btn1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(0, 307, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btn1.setObjectName("btn1")
        self.btn3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(200, 307, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(0, 207, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(100, 207, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(200, 207, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btn6.setObjectName("btn6")
        self.btn9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(200, 108, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btn9.setObjectName("btn9")
        self.btn8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(100, 108, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btn8.setObjectName("btn8")
        self.btn7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(0, 108, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 700 24pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"color: rgb(0, 170, 0);\n"
"color: rgb(2, 188, 255);")
        self.btn7.setObjectName("btn7")
        self.btnPlus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPlus.setGeometry(QtCore.QRect(300, 406, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btnPlus.setFont(font)
        self.btnPlus.setStyleSheet("font: 700 24pt \"Arial\";\n"
"background-color: rgb(170, 255, 127);\n"
"color: rgb(0, 170, 0);")
        self.btnPlus.setObjectName("btnPlus")
        self.btnMinus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMinus.setGeometry(QtCore.QRect(300, 307, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btnMinus.setFont(font)
        self.btnMinus.setStyleSheet("font: 700 24pt \"Arial\";\n"
"background-color: rgb(170, 255, 127);\n"
"color: rgb(0, 170, 0);")
        self.btnMinus.setObjectName("btnMinus")
        self.btnMulti = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMulti.setGeometry(QtCore.QRect(300, 207, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btnMulti.setFont(font)
        self.btnMulti.setStyleSheet("font: 700 24pt \"Arial\";\n"
"background-color: rgb(170, 255, 127);\n"
"color: rgb(0, 170, 0);")
        self.btnMulti.setObjectName("btnMulti")
        self.btnDivide = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDivide.setGeometry(QtCore.QRect(300, 108, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btnDivide.setFont(font)
        self.btnDivide.setStyleSheet("font: 700 24pt \"Arial\";\n"
"background-color: rgb(170, 255, 127);\n"
"color: rgb(0, 170, 0);")
        self.btnDivide.setObjectName("btnDivide")
        self.btnCe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCe.setGeometry(QtCore.QRect(0, 58, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btnCe.setFont(font)
        self.btnCe.setStyleSheet("font: 700 24pt \"Arial\";\n"
"background-color: rgb(255, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.btnCe.setObjectName("btnCe")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.result.setText(_translate("MainWindow", "0"))
        self.btnZero.setText(_translate("MainWindow", "0"))
        self.btnEqual.setText(_translate("MainWindow", "="))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btnPlus.setText(_translate("MainWindow", "+"))
        self.btnMinus.setText(_translate("MainWindow", "-"))
        self.btnMulti.setText(_translate("MainWindow", "*"))
        self.btnDivide.setText(_translate("MainWindow", "/"))
        self.btnCe.setText(_translate("MainWindow", "CE"))
    
    def add_functions(self):
                self.btnZero.clicked.connect(lambda: self.write_number(self.btnZero.text()))
                self.btn1.clicked.connect(lambda: self.write_number(self.btn1.text()))
                self.btn2.clicked.connect(lambda: self.write_number(self.btn2.text()))
                self.btn3.clicked.connect(lambda: self.write_number(self.btn3.text()))
                self.btn4.clicked.connect(lambda: self.write_number(self.btn4.text()))
                self.btn5.clicked.connect(lambda: self.write_number(self.btn5.text()))
                self.btn6.clicked.connect(lambda: self.write_number(self.btn6.text()))
                self.btn7.clicked.connect(lambda: self.write_number(self.btn7.text()))
                self.btn8.clicked.connect(lambda: self.write_number(self.btn8.text()))
                self.btn9.clicked.connect(lambda: self.write_number(self.btn9.text()))
                self.btnPlus.clicked.connect(lambda: self.write_number(self.btnPlus.text()))
                self.btnMinus.clicked.connect(lambda: self.write_number(self.btnMinus.text()))
                self.btnMulti.clicked.connect(lambda: self.write_number(self.btnMulti.text()))
                self.btnDivide.clicked.connect(lambda: self.write_number(self.btnDivide.text()))
                self.btnEqual.clicked.connect(lambda: self.Result())
                self.btnCe.clicked.connect(lambda: self.result.setText("0"))
                

    def write_number(self, number):
        if self.result.text() == "0":
            self.result.setText(number)
        else:
            self.result.setText(self.result.text() + number)

    def Result(self):
        str_ = self.result.text()
        if str_.find("/0") == True:
             error = QMessageBox()
             error.setWindowTitle("Ошибка!")
             error.setText("На ноль делить нельзя!")
             error.setIcon(QMessageBox.Icon.Warning)
             error.exec()
             self.result.setText("0")
        else:
                res = eval(self.result.text())#eval - вычисляет строковое выражение
                self.result.setText(str(res))

             #error = QMessageBox()
             #error.setWindowTitle("Ошибка!")
             #error.setText("Сейчас это невозможно!")
             #error.exec()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
